[[redirects]]
  from = "/api/*"
  to = "https://SEU_BACKEND.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://SEU_BACKEND.up.railway.app/socket.io/:splat"
  status = 200
  force = true